### ISSUE TITLE
FEAT: Connect to the server and try POST

### ISSUE THREAD

**Issue by world2222** [Beinus/Android#3]
# Description
* Connect to the spring server and try using POST send the new employee's info to database.
<br>

# Todo
- [x] Implement API connection (service, implementation, Ktor)
- [x] Implement Dependency Injection
- [x] Implement Login Screen
- [x] Check if the POST working well by touching a button
