### ISSUE TITLE
FEAT: Implement login and signup

### ISSUE THREAD

**Issue by world2222** [Beinus/Android#5]
# Description
* Implement the login and signup screen. If the id and password matches, users can enter the main screen and see the users whose data are saved in the database.
<br>

# Todo
- [x] Update the names of the data following the updated data in server.
- [x] Implement login screen and signup screen.
- [x] Implement the logic of each screen by using the server.
- [x] Show the data of the users in the database on the HomeScreen.
